function uimake(varargin)
    global molecule
    if ~isempty(varargin)
        molecule = varargin{1};
    else
        molecule = struct();
    end
    load('data.mat');
    fig = figure('Units','normalized',...
                 'Position',[0 0.0463 1 .8666]);
    ax = axes('Units','normalized',...
              'Position',[.01,.11,.98,.88]);
    axis(ax,'off');
    tabs = uitabgroup('Parent',fig,...
                      'Position',[.01,.01,.19,.09]);
    tab1 = uitab('Parent',tabs,...
                 'Title','Edit Elements');
    uicontrol('Parent',tab1,...
              'Style','popupmenu',...
              'String',[{'~Please Choose~'} fieldnames(molecule)],...
              'FontSize',12,...
              'Units','normalized',...
              'Position',[.01 .2 .58 .6]);
    uicontrol('Parent',tab1,...
              'Style','pushbutton',...
              'String','Edit',...
              'FontSize',12,...
              'Units','normalized',...
              'Position',[.61 .2 .38 .6],...
              'Callback',@editfcn);
	tab2 = uitab('Parent',tabs,...
                'Title','Add Elements');
    uicontrol('Parent',tab2,...
              'Style','popupmenu',...
              'String',{st.Name},...
              'FontSize',12,...
              'Units','normalized',...
              'Position',[.01 .2 .58 .6]);
    uicontrol('Parent',tab2,...
              'Style','pushbutton',...
              'String','Add',...
              'FontSize',12,...
              'Units','normalized',...
              'Position',[.61 .2 .38 .6],...
              'Callback',@addfcn);
end

function editfcn(ui,~)
    global molecule
    

end

function addfcn(ui,~)
    global molecule


end

function draw
    global molecule

end